# Name of the workflow
name: Hello World Workflow

# Events that trigger this workflow
on:
  # Trigger when code is pushed to the main branch
  push:
    branches: [main]
  
  # Trigger when a pull request targets main or staging branches
  pull_request:
    branches: [main, staging]

# Jobs to run
jobs:
  greet:
    # The type of runner to use (Linux, Windows, Mac)
    runs-on: ubuntu-latest
    
    # Steps to execute in this job
    steps:
      # Step 1: run a single line command
      - name: Hello
        run: echo "hello world!"   # Print hello world in workflow logs
